#!/usr/bin/env python3
"""
Extract a representative color for each OSRS Leagues area badge.

The badges are small (20x30) pixel-art icons with a dark near-black shield
border and a white-ish sparkle/inner stroke. We want a color that represents
the *interior fill*, not the border or highlight, so downstream UI chips
read as distinct from each other.

Strategy:
  1. Load each badge and flatten over a dark UI background.
  2. Drop fully-transparent pixels, plus pixels that are nearly-black
     (shield border) or nearly-white (sparkle highlights / cross strokes).
  3. Pick the dominant color cluster via a coarse 24-bit quantization
     (bucket per 16 on each channel), then refine by averaging all
     pixels in that bucket. This reliably returns a punchy, saturated
     fill color rather than a muddy mean.
  4. Print a TypeScript-ready color map plus a preview HTML swatch.
"""
from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

from PIL import Image

REGIONS = [
    "varlamore", "karamja", "asgarnia", "desert", "fremennik",
    "kandarin", "kourend", "morytania", "tirannwn", "wilderness",
    "misthalin",
]

BADGE_DIR = Path(__file__).parent.parent / "public" / "icons" / "region"


def dominant_color(path: Path) -> tuple[int, int, int]:
    img = Image.open(path).convert("RGBA")
    pixels = list(img.getdata())
    # Bucket interior pixels (alpha present, not near-black border,
    # not near-white highlight) at a 16-step coarseness.
    buckets: Counter[tuple[int, int, int]] = Counter()
    bucket_pixels: dict[tuple[int, int, int], list[tuple[int, int, int]]] = {}
    for r, g, b, a in pixels:
        if a < 200:
            continue
        brightness = (r + g + b) / 3
        if brightness < 35:
            continue  # border / shadow
        if brightness > 235 and abs(r - g) < 12 and abs(g - b) < 12:
            continue  # sparkle highlight
        key = (r // 8, g // 8, b // 8)
        buckets[key] += 1
        bucket_pixels.setdefault(key, []).append((r, g, b))
    if not buckets:
        return (128, 128, 128)
    top_key = buckets.most_common(1)[0][0]
    px = bucket_pixels[top_key]
    r = sum(p[0] for p in px) // len(px)
    g = sum(p[1] for p in px) // len(px)
    b = sum(p[2] for p in px) // len(px)
    return (r, g, b)


def lighten(rgb: tuple[int, int, int], amount: float) -> tuple[int, int, int]:
    """Move toward white by `amount` (0..1). Used for chip text colors."""
    r, g, b = rgb
    return (
        min(255, int(r + (255 - r) * amount)),
        min(255, int(g + (255 - g) * amount)),
        min(255, int(b + (255 - b) * amount)),
    )


def hex_of(rgb: tuple[int, int, int]) -> str:
    return "#{:02x}{:02x}{:02x}".format(*rgb)


def main() -> int:
    print("// Region palette, derived from the authentic OSRS Leagues area badges.")
    print("// Generated by scripts/extract-region-colors.py — don't hand-edit.")
    print()
    print("REGION_COLOR (base / border):")
    for r in REGIONS:
        p = BADGE_DIR / f"{r}.png"
        if not p.exists():
            print(f"  // {r}: MISSING {p}")
            continue
        base = dominant_color(p)
        text = lighten(base, 0.55)
        print(f"  {r:11s} base {hex_of(base)}  text {hex_of(text)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
